In [1]:
from tensorflow.keras.models import load_model   #can use joblib
import numpy as np
import cv2
model = load_model('chahat.h5')
model.compile(optimizer = 'adam',loss='categorical_crossentropy',metrics=['accuracy']) 

In [2]:
from skimage.transform import resize
def detect(frame):
    try:
        img = resize(frame,(64,64))
        img = np.expand_dims(img,axis=0)
        if(np.max(img)>1):
            img = img/255.0
        prediction = model.predict(img)    
        print(prediction)
        prediction_class = model.predict_classes(img)
        print(prediction_class)   #gives class name
    except AttributeError:
        print("Shape not found")

In [3]:
frame = cv2.imread(r'C:\Users\chaha\Desktop\dataset\testset\humming_birds\humm.jpg') #to read image
data = detect(frame)

[[1.5928933e-01 2.4604335e-10 6.1281568e-01 8.5594017e-08 2.2789493e-01]]
[2]


In [4]:
frame = cv2.imread(r'C:\Users\chaha\Desktop\dataset\testset\parrots\3.jpg') #to read image
data = detect(frame)

[[6.5388152e-19 5.1672263e-26 5.8866076e-27 1.6581654e-20 1.0000000e+00]]
[4]


In [5]:
frame = cv2.imread(r'C:\Users\chaha\Desktop\dataset\testset\doves\50.jpg') #to read image
data = detect(frame)

[[1.0000000e+00 3.3575107e-13 4.9580945e-10 8.4512446e-11 1.1969730e-12]]
[0]


In [8]:
frame = cv2.imread(r'C:\Users\chaha\Desktop\dataset\testset\owls\3.jpg') #to read image
data = detect(frame)

[[4.2332880e-02 1.6355910e-06 8.6131605e-12 9.5766550e-01 3.9514881e-11]]
[3]
